
-
  name:  'Fileprovider'
  uriPattern: 'neos/techdivision-docviewer/{package}/{filePath}'
  defaults:
    '@package':    'TechDivision.DocViewer'
    '@controller': 'Resource'
    '@action':     'raw'
  httpMethods: ['GET']
