
-
  name:  'Fileprovider'
  uriPattern: 'techdivision-docviewer/{packageType}/{packageKey}/{filePath}'
  defaults:
    '@package':    'TechDivision.DocViewer'
    '@controller': 'Resource'
    '@action':     'raw'
  httpMethods: ['GET']