Neos:
  Neos:
    modules:
      management:
        submodules:
          techDivisionDocViewer:
            label: 'TechDivision.DocViewer:Main:module.label'
            controller: '\TechDivision\DocViewer\Controller\ModuleController'
            action: 'list'
            description: 'TechDivision.DocViewer:Main:module.description'
            icon: 'icon-book'
            privilegeTarget: 'TechDivision.DocViewer:Module'
    userInterface:
      translation:
        autoInclude:
          'TechDivision.DocViewer': ['Main']
  Flow:
    mvc:
      routes:
        'TechDivision.DocViewer':
          position: 'before Neos.Neos'
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'TechDivision.DocViewer:controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'TechDivision\DocViewer\Controller\.*'


TechDivision:
  DocViewer:
    packages:
      # Try to show this package by default
      #entryPackage: 'TechDivision.DocViewer'
      # defines which types of packages are visible in which order
      visibleTypes: [ 'Sites', 'Application' ]

      # All listed packages gets' hided and are not accessable
      hide:
        - Neos.Imagine
        - Neos.Media
        - Neos.Form
        - Neos.Twitter.Bootstrap
        - Neos.Neos
       # - TechDivision.DocViewer

    # Files are searched for as entry file
    entryFiles: [ 'Readme', 'index', 'Index' ]

    parser:
      markdown:
        allowedFileExtensions: [ 'md', 'rst', 'txt' ]