TYPO3:
  Neos:
    modules:
      management:
        submodules:
          techDivisionDocViewer:
            label: 'TechDivision.DocViewer:Main:module.label'
            controller: '\TechDivision\DocViewer\Controller\ModuleController'
            description: 'TechDivision.DocViewer:Main:module.description'
            icon: 'icon-book'
            privilegeTarget: 'TechDivision.DocViewer:Module'
    userInterface:
      translation:
        autoInclude:
          'TechDivision.DocViewer': ['Main']
  Flow:
    mvc:
      routes:
        'TechDivision.DocViewer':
          position: 'before TYPO3.Neos'
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              'TechDivision.DocViewer:controllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'TechDivision\DocViewer\Controller\.*'


TechDivision:
  DocViewer:
    packages:
      # defines which types of packages are visible in which order
      visibleTypes: [ 'Sites', 'Application' ]
      hide:
        - TYPO3.TypoScript
        - TYPO3.Imagine
        - TYPO3.Media
        - TYPO3.Form
        - TYPO3.Twitter.Bootstrap
        - TYPO3.Neos
        - TYPO3.Fluid
        - TYPO3.Eel
        - TYPO3.Flow
       # - TechDivision.DocViewer
    # Files are searched for as entry file
    entryFiles: [ 'Readme', 'index', 'Index' ]
    parser:
      markdown:
        allowedFileExtensions: [ 'md', 'rst', 'txt' ]